on:
  workflow_dispatch:

name: Benchmarks

env:
  RUSTFLAGS: "-D warnings"

jobs:
  # TODO: Figure out how to visualize these benchmarks somewhere
  benchmarks:
    name: cargo bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup toolchain install stable --no-self-update --profile minimal
      - uses: Swatinem/rust-cache@v2

      - name: Benchmark
        run: cargo bench
