on:
  workflow_dispatch:

name: Benchmarks

env:
  RUSTFLAGS: "-D warnings"

jobs:
  # TODO: Figure out how to visualize these benchmarks somewhere
  benchmarks:
    name: cargo bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: bench
