on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: CI

env:
  RUSTFLAGS: "-D warnings"
  PROPTEST_CASES: 10000
  MIRIFAGS: "-Zmiri-tag-raw-pointers -Zmiri-check-number-validity"

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --tests --all-features

  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-cargo-test-v3
      - name: Install cargo-nextest
        run: |
          which cargo-nextest || cargo install cargo-nextest
      - name: cargo test
        run: |
          cargo nextest run --release --all-features --manifest-path=compact_str/Cargo.toml --run-ignored=all

  test-nightly:
    name: cargo test nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-cargo-test-nightly-v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --release --all-features --manifest-path=compact_str/Cargo.toml -- --include-ignored

  miri:
    name: cargo miri test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-cargo-miri-v2
      - name: Run Miri
        run: |
          cargo miri test --all-features --manifest-path=compact_str/Cargo.toml

  example-bytes:
    name: example - bytes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path examples/bytes/Cargo.toml

  example-serde:
    name: example - serde
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path examples/serde/Cargo.toml
