name: no-std

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  no-std:
    name: no-std build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opt: ["", "--release"]
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup toolchain install stable --no-self-update --profile minimal --target thumbv6m-none-eabi

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.opt }}

      - run: |
          cargo check --lib --manifest-path compact_str/Cargo.toml --no-default-features ${{ matrix.opt }} --target thumbv6m-none-eabi
