on:
  push:
    tags:
    - '*'
  workflow_dispatch:

name: Release

env:
  CARGO_TERM_COLOR: "always"
  RUSTFLAGS: "-D warnings"

jobs:
  feature_powerset:
    name: cargo check feature-powerset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup toolchain install stable --no-self-update --profile minimal
      - name: Install cargo hack
        uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2

      - name: cargo test msrv..
        run: |
          cd compact_str
          cargo hack check --feature-powerset --optional-deps
